---
- name: Create clickhouse-backup cronjob bash script
  template:
    src: cronjob-clickhouse-backup.sh.j2
    dest: "/usr/local/bin/cronjob-clickhouse-backup-{{ item }}.sh"
    owner: root
    group: root
    mode: '0775'
  loop:
    - daily
    - weekly
    - monthly

- name: Set default state for clickhouse-backup cron file
  set_fact:
    clickhouse_backup_crontab_state: absent

- name: Overwrite state for clickhouse-backup cron file
  set_fact:
    clickhouse_backup_crontab_state: present
  when: clickhouse_backup_install_crontab

- name: Creates/remove cron file under /etc/cron.d
  cron:
    name: Add cronjob for clickhouse backup
    special_time: "{{ item }}"
    user: root
    job: "/usr/local/bin/cronjob-clickhouse-backup-{{ item }}.sh"
    cron_file: "clickhouse-backup-{{ item }}"
    state: "{{ clickhouse_backup_crontab_state }}"
  loop:
    - daily
    - weekly
    - monthly
