---
driver:
  name: hetznercloud
lint: |
  set -e
  yamllint .
platforms:
  - name: ${MOLECULE_TEST_SCOPE:-default}-clickhouse
    server_type: cx11
    image: ${MOLECULE_PLATFORM}
    groups:
      - clickhouse
      - clickhouse_data
  - name: ${MOLECULE_TEST_SCOPE:-default}-clickhouse-restore
    server_type: cx11
    image: ${MOLECULE_PLATFORM}
    groups:
      - clickhouse
      - clickhouse_restore
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      clickhouse:
        clickhouse_kafka_client_users:
          - username: guest
            password: guest
        clickhouse_backup_version: 0.5.2
        clickhouse_backup_general_remote_storage: gcs
        clickhouse_backup_gcs_credentials_file: /etc/clickhouse-backup-gcs-credentials.json
        clickhouse_backup_gcs_bucket: sib-clickhouse-backup-ci
        clickhouse_backup_gcs_path: "${MOLECULE_TEST_SCOPE:-default}"
  lint: |
    set -e
    ansible-lint
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml
    verify: verify/main.yml
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
