---
- name: Check that clickhouse-backup cronjob file is created
  stat:
    path: "/etc/cron.d/clickhouse-backup-{{ item }}"
  register: stat_cronjob_result
  failed_when: not stat_cronjob_result.stat.exists
  loop:
    - daily
    - weekly
    - monthly

- name: Run cronjob script
  command: /usr/local/bin/cronjob-clickhouse-backup-daily.sh
  register: cronjob_script_result
  run_once: yes

- name: Verify cronjob script return code
  assert:
    that:
      - cronjob_script_result.rc == 0
