---
- name: Check example dataset
  shell: "clickhouse-client -h {{ ansible_default_ipv4.address }} --query 'SELECT COUNT(*) FROM datasets.visits_v1'"
  register: dataset_out

- name: Verify number of records in example dataset
  assert:
    that:
      - dataset_out.stdout | int > 1500000
